
swagger:
  enabled=true

server:
  port : 18080

spring:
  kafka:
    properties:
      bootstrap-servers:
        - localhost:9092
      schema.registry.url: http://localhost:8081
    consumer:
      group-id: passengerConsumers
      auto-offset-reset: latest
#      specific-avro-reader: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic:



