/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.vwgis.kafkatitanixexercise.model;
@org.apache.avro.specific.AvroGenerated
public enum Gender implements org.apache.avro.generic.GenericEnumSymbol<Gender> {
  male, female, diverse  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Gender\",\"namespace\":\"de.vwgis.kafkatitanixexercise.model\",\"symbols\":[\"male\",\"female\",\"diverse\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
